from time import sleep
from base.BasePage import BasePage
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pyautogui
from pywinauto import application
from pywinauto.win32functions import SetFocus
from pywinauto import mouse

class autoShutdownPage(BasePage):
    labname = (By.LINK_TEXT, 'ding0911-e-1')
    configuration = (By.XPATH, '//div[text()="Configuration and policies"]')
    auto_shutdown = (By.XPATH, '//div[text()="Auto-shutdown"]')
    auto_radio = (By.XPATH, '//span[@class="azc-radio-circle"]')
    shutdown_time = (By.XPATH, '//input[@placeholder="h:mm:ss AM/PM"]')
    save_button = (By.XPATH, '//div[@title="Save"]')
    close_button1 = (By.XPATH, '//button[@aria-label="Dismiss toast notification"]')
    close_button2 = (By.XPATH, '//button[@title="Close"]')
    refresh_button = (By.XPATH, '//div[text()="Refresh"]')
    email_address = (By.XPATH, '//input[@aria-label="Email address"]')
    vm_button1 = (By.LINK_TEXT, 'ding-win')
    vm_button2 = (By.LINK_TEXT, 'ding-pr000')
    vm_button3 = (By.LINK_TEXT, 'ding-pu000')
    start_button = (By.XPATH, '//div[@title="Start"]')
    webhook_url = (By.XPATH, '//input[@aria-label="Webhook URL"]')
    url = 'https://ms.portal.azure.com/#browse/Microsoft.DevTestLab%2Flabs'

    def __init__(self, driver):
        BasePage.__init__(self, driver)

    def goto_dtl_page(self):
        self.open_url(self.url)
        self.driver.maximize_window()
        WebDriverWait(self.driver, 15, 0.5).until(EC.presence_of_element_located((self.labname)))
        self.click_element(*self.labname)

    def set_autoshutdown(self):
        WebDriverWait(self.driver, 30, 0.5).until(EC.presence_of_element_located((self.configuration)))
        self.click_element(*self.configuration)
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//div[text()="Auto-shutdown"]')), 'Auto-shutdown'))
        self.click_element(*self.auto_shutdown)
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//label[text()="Enabled"]')), 'Enabled'))
        enable_radio = self.locate_elements(*self.auto_radio)
        enable_radio[0].click()
        self.clear_text(*self.shutdown_time)
        self.type_text('14:52:00 pM', *self.shutdown_time)
        pyautogui.click(600, 600)
        sleep(2)
        self.click_element(*self.save_button)
        WebDriverWait(self.driver, 50, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ("//div[text()='Update of schedule successful']")), 'Update of schedule successful'))
        self.click_element(*self.close_button1)
        sleep(2)
        close_list = self.locate_elements(*self.close_button2)
        close_list[2].click()  
        sleep(300)
        refresh = self.locate_elements(*self.refresh_button)
        refresh[1].click()
        # 开启win虚拟机
        sleep(3)
        WebDriverWait(self.driver, 30, 0.5).until(EC.presence_of_element_located((self.vm_button1)))
        self.click_element(*self.vm_button1)
        WebDriverWait(self.driver, 30, 0.5).until(EC.presence_of_element_located((self.start_button)))
        self.click_element(*self.start_button)
        WebDriverWait(self.driver, 240, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ("//div[text()='Started virtual machine']")), 'Started virtual machine'))
        self.click_element(*self.close_button1)
        sleep(2)
        close_list = self.locate_elements(*self.close_button2)
        close_list[2].click()
        sleep(2)

        #开启pr虚拟机
        WebDriverWait(self.driver, 50, 0.5).until(EC.presence_of_element_located((self.vm_button2)))
        self.click_element(*self.vm_button2)
        WebDriverWait(self.driver, 50, 0.5).until(EC.presence_of_element_located((self.start_button)))
        self.click_element(*self.start_button)
        WebDriverWait(self.driver, 240, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ("//div[text()='Started virtual machine']")), 'Started virtual machine'))
        self.click_element(*self.close_button1)
        sleep(2)
        close_list = self.locate_elements(*self.close_button2)
        close_list[2].click()
        sleep(2)
        # 开启pu虚拟机
        WebDriverWait(self.driver, 50, 0.5).until(EC.presence_of_element_located((self.vm_button3)))
        self.click_element(*self.vm_button3)
        WebDriverWait(self.driver, 50, 0.5).until(EC.presence_of_element_located((self.start_button)))
        self.click_element(*self.start_button)
        WebDriverWait(self.driver, 240, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ("//div[text()='Started virtual machine']")), 'Started virtual machine'))
        self.click_element(*self.close_button1)
        sleep(2)
        close_list = self.locate_elements(*self.close_button2)
        close_list[2].click()
        sleep(2)

        refresh = self.locate_elements(*self.refresh_button)
        refresh[1].click()
        sleep(3)
        
    def set_emailshutdown(self):
        WebDriverWait(self.driver, 50, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//div[text()="Configuration and policies"]')), 'Configuration and policies'))
        self.click_element(*self.configuration)
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//div[text()="Auto-shutdown"]')), 'Auto-shutdown'))
        self.click_element(*self.auto_shutdown)
        WebDriverWait(self.driver, 50, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//label[text()="Enabled"]')), 'Enabled'))
        notification_radio = self.locate_elements(*self.auto_radio)
        notification_radio[2].click()
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//label[text()="Email address"]')), 'Email address'))
        self.type_text('v-yuhanding@microsoft.com', *self.email_address)
        self.clear_text(*self.shutdown_time)
        self.type_text('15:40:00 pM', *self.shutdown_time)
        pyautogui.click(600, 800)
        sleep(2)
        self.click_element(*self.save_button)
        WebDriverWait(self.driver, 50, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ("//div[text()='Update of schedule successful']")), 'Update of schedule successful'))
        self.click_element(*self.close_button1)
        sleep(2)
        close_list = self.locate_elements(*self.close_button2)
        close_list[2].click()
        sleep(240)
        app = application.Application().start(r'C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE')
        outlook_window = app.window(title=u"Opening - Outlook", class_name='MsoSplash')
        outlook_window.set_focus()
        sleep(7)
        mouse.click(coords=(600,350))
        sleep(2)
        mouse.click(coords=(1390,550))
        mouse.click(coords=(950,425))
        sleep(6)
        app.kill()

    def set_webhook(self):
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//div[text()="Configuration and policies"]')), 'Configuration and policies'))
        self.click_element(*self.configuration)
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//div[text()="Auto-shutdown"]')), 'Auto-shutdown'))
        self.click_element(*self.auto_shutdown)
        WebDriverWait(self.driver, 30, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ('//label[text()="Enabled"]')), 'Enabled'))
        self.clear_text(*self.email_address)
        self.type_text('https://microsoft.webhook.office.com/webhookb2/3db9d97b-a19c-412d-bc3d-785dd0315657@72f988bf-86f1-41af-91ab-2d7cd011db47/IncomingWebhook/53ceb74d4e054c889a4c6675236aa0e0/a1b3f01d-8569-437c-a830-736b33d0ac1e', *self.webhook_url)
        self.clear_text(*self.shutdown_time)
        self.type_text('16:15:00 pM', *self.shutdown_time)
        pyautogui.click(600, 800)
        sleep(2)
        self.click_element(*self.save_button)
        WebDriverWait(self.driver, 50, 0.5).until(EC.text_to_be_present_in_element((By.XPATH, ("//div[text()='Update of schedule successful']")), 'Update of schedule successful'))
        self.click_element(*self.close_button1)
        sleep(2)
        close_list = self.locate_elements(*self.close_button2)
        close_list[2].click()
        sleep(240)
        application.Application().start(r'C:\Users\v-yuhanding\AppData\Local\Microsoft\Teams\Update.exe --processStart "Teams.exe"')
        sleep(2) 
        mouse.click(coords=(25,200))
        mouse.click(coords=(700,450))
        sleep(6)
        pyautogui.click(1600, 10)